#!/usr/bin/env bash
# This script displays information about subdomains.

# Function to get subdomain information
get_subdomain_info() {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$dig_output" | awk '/IN/ {print $4}')
    destination=$(echo "$dig_output" | awk '/IN/ {print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script logic
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomain_list=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomain_list[@]}"; do
        get_subdomain_info "$domain" "$sub"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi
