#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp.

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Disable strict host key checking
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "${USERNAME}@$IP":~/
