#!/usr/bin/env bash

# Define the frontend and backend configurations
CONFIG="
frontend myfrontend
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
   balance roundrobin
   server 236784-web-01 54.208.23.186:80 check
   server 236784-web-02 18.234.80.12:80 check
"
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
printf "%s" "$CONFIG" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
