#!/usr/bin/env bash
# This script stops the "4-to_infinity_and_beyond" process using pkill.

# Use pkill to find and terminate the "4-to_infinity_and_beyond" process
pkill -f "4-to_infinity_and_beyond"

echo "Terminated"
