#!/usr/bin/env bash
# This script displays specific information from /etc/passwd

while IFS=':' read -r username x userid x x home_path x; do
    echo "$username:$userid:$home_path"
done < /etc/passwd
