#!/usr/bin/env bash

# Update /etc/hosts file to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
# (To be run in a Docker container; else revert host file back)

HOST_FILE="/etc/hosts"
TEMP_FILE=$(mktemp)
LOCAL_HOST="127.0.0.2	localhost"
FACEBOOK="8.8.8.8	facebook.com"

# Change localhost and facebook.com entries in the temporary file
sed "/127\.0\.0\.1/ s/.*/$LOCAL_HOST/" "$HOST_FILE" > "$TEMP_FILE"
sed "/facebook\.com/ s/.*/$FACEBOOK/" "$TEMP_FILE" > "$HOST_FILE"

# Clean up temporary file
rm "$TEMP_FILE"